### ISSUE TITLE
weirdness when completing a different token when starting at the start of a token

### ISSUE THREAD

**Issue by joelrbrandt** [iwehrman/brackets-simple-js-code-hints#2]
**Steps to reproduce**

``` javascript
function () {
    var foo = 42;
    var bar = 43;
    foo;
}
```
1. Put the insertion point before the 'f' in 'foo'.
2. Hit command-space
3. complete to 'bar'.

**Actual**

File becomes:

``` javascript
function () {
    var foo = 42;
    var bar = 43;
barfoo;
}
```

**Expected**

File becomes:

``` javascript
function () {
    var foo = 42;
    var bar = 43;
    bar;
}
```

**Comment by iwehrman** [comment]
Fixed by https://github.com/iwehrman/brackets-js-code-hints/commit/ccdf7ad7cff39b4c6d14d402e7cae2ab160f804e.
