### ISSUE TITLE
StringUtils.htmlEscape() has been removed

### ISSUE THREAD

**Issue by le717** [iwehrman/brackets-simple-js-code-hints#7]
After a long deprecation phase, `StringUtils.htmlEscape()` has been removed. This extension makes use of this removed API. You will want to update it to use `_.escape()` instead to prevent your extension from breaking. Full details are at adobe/brackets#8960.

-le717

**Comment by peterflynn** [comment]
@iwehrman Note, this means the extension will not work in Brackets 1.0 since `formatHints()` will throw an exception.  It's an easy fix though.
